# For Windows setup
test -f ~/.aliases && . ~/.functions
test -f ~/.aliases && . ~/.aliases

# Unbreak broken, non-colored terminal
export TERM=xterm-256color

# Don't use ^D to exit
set -o ignoreeof

# Needed for mingw32
export PATH=$HOME/bin/:$HOME/.dotfiles/bin:$PATH

# TMP and TEMP are defined in the Windows environment. Leaving them set to the default
# Windows temporary directory can have unexpected consequences.
export TMP=/tmp
export TEMP=/tmp
export TMPDIR=/tmp

cd ~
